#%RAML 0.8
title: System API
version: v1.0

schemas:
  - account: !include schemas/account_schema.json

traits: !include ./traits/trait-collection.yaml

/migrateAccounts:
  displayName: migrateAccounts
  post:
    description: |
      Migrate all accounts on the input
    body:
      application/json:
        example: !include ./examples/account_collection_example.json
    responses:
      201:
        description: Migrated
        body:
          application/json:
            example: |
              {
                "message": "Accounts were successfully migrated."
              }
/migrateAccountsB:
  displayName: migrateAccountsB
  post:
    description: |
      Migrate accounts from A instance to B instance
    queryParameters:
      modifiedAfter:
        displayName: Only those modified after this date
        minLength: 23
        maxLength: 29
        example: 2016-03-24T14:00:00.000+01:00
    responses:
      201:
        description: Migrated
        body:
          application/json:
            example: |
              {
                "message": "Accounts were successfully migrated."
              }